<div class="container">
	<div class="row">
	  <div class="col-md-12">

    <div class="page-header">
		<div class="row">
			<div class="col-md-6">
				<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div>
			<div class="col-md-6 text-right">
				<a href="/<?php echo $this->ruta;?>/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:#2eacce;"></span> <br><?php echo $this->title;?></a>
			</div>
			
		</div>
	</div>
	  </div>
	  <div class="col-md-4">
		<form name="form1" id="form1" method="post" action="" autocomplete="off">
		  <div class="form-group">
			<label for="nombre">Nombre</label>
			<input type="hidden" class="form-control" id="tipo" name="tipo" value="0" >
			<input type="hidden" class="form-control" id="id" name="id">
			<input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre de la Marca" required >
		  </div>
		  <div class="form-group"> 
			<label for="telefono">Estado</label>
			
			<select id="estado" name="estado" class="form-control" required >
				<option value="">Seleccionar Estado</option>
				<option value="1">Activo</option>
				<option value="0">Inactivo</option>
			</select>
			
		  </div>  
		  <button type="submit" class="btn btn-primary">Guardar</button>
		</form>
	  </div>

	</div>
</div>



