<div class="container">
<div class="row">
  <div class="col-md-12">

    <div class="page-header">
		<div class="row">
			<div class="col-md-6">
				<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div>
			<div class="col-md-6 text-right">
				<a href="/productos/descuento/nuevo/" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:#2eacce;"></span> <br>Añadir Descuento</a>
			</div>			
		</div>
	</div>
  </div>

  <div class="col-md-12">
    <div class="panel panel-default">
    <div class="panel-body">
      <!-- Table -->
      <table class="table table-bordered table-hover" id="table-descuentos">
        <thead>
        <tr>
          <th>Código</th>
          <th>Descripción</th>
          <th>Fecha Inicio</th>
          <th>Fecha Fin</th>
          <th>Tipo - Valor</th>
          <th>Estado</th>
		  
        </tr>
        </thead>

        <tbody>
        </tbody>  

      </table>
    </div>
  </div>
</div>
</div>
</div>