<div class="container">
<div class="row-fluid">
  <div class="col-md-12">
    <div class="page-header">
		<div class="row">
			<div class="col-md-6">
				<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div>
			<div class="col-md-6 text-right">
				<a href="/productos/nuevo/" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:#2eacce;"></span> <br>Añadir producto</a>
			</div>			
		</div>
	</div> 
  </div>
  
  
  <div class="col-md-12">
    <div class="panel panel-default">
	
		<div class="panel-body">
		  <!-- Table -->
		  <table class="table table-hover table-bordered" id="table-producto">
			<thead>
			<tr>
			  <th>Código SKU</th>	
			  <th>Imagen</th>	
			  <th>Nombre</th>
			  <th>Categoría</th>
			  <th>Precio Normal</th>
			  <th>Precio Oferta</th>
			  <th>Cantidad (Stock)</th>
			  <th>Estado</th>
			  <th style="width:130px;"></th>
			</tr>
			</thead>

			<tbody>
			  <?php if (count($this->producto)) { ?>
				  <?php foreach ($this->producto as $aux) { ?>    
					<tr>
					  <td><?php echo $aux->sku;?></td>
					  <td><a href="<?php echo $aux->imagen;?>" class="image-link"><img src="<?php echo $aux->imagen;?>"  style="width:70px;height:50px;"></a></td>
					  <td><?php echo $aux->nombre;?></td>
					  <td><?php echo $aux->categoria;?></td>
					  <td><?php echo "$".formatearValor($aux->valor);?></td>
					  <td><?php echo "$".formatearValor($aux->valor_rebaja);?></td>
					  <td><?php echo $aux->stock;?></td>
					  <td><?php echo ($aux->estado!=1)?"<span class='glyphicon glyphicon-remove'  style='color:red;'></span>":"<psan class='glyphicon glyphicon-ok' style='color:green;'></span>";?></td>
					  
					  <td> 
						<div class="btn-group">
						  <button type="button" class="btn btn-default btn-sm btn-editar" value="<?php echo $aux->id;?>" ><span class="glyphicon glyphicon-pencil" aria-hidden="true" style="color:#555;"></span> Modificar</button>
						  <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<span class="caret"></span>
							<span class="sr-only">Toggle Dropdown</span>
						  </button>
						  <ul class="dropdown-menu">
							<li><a href="/productos/eliminar/<?php echo $aux->id;?>/" class="eliminar"><span class="glyphicon glyphicon-trash" aria-hidden="true" style="color:#555;"></span> Eliminar</a></li>
						  </ul>
						</div>
						
					  </td> 
					</tr>
				  <?php } ?>
			  <?php }else{ ?>
					<tr>
					  <td colspan="8" align="center">No existen Productos</td>
					</tr>
			  <?php } ?>
			  
			</tbody>  

		  </table>
		</div>
	</div>
  </div>
 
</div>
</div>
