<div class="container">
  <div class="col-md-12">
			<div class="page-header">
				<div class="row">
					<div class="col-md-4 col-sm-4 col-xs-6">
					<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
					</div>
					<div class="col-md-6 col-md-offset-2 col-sm-6 col-sm-offset-2 col-xs-6 text-right">
						<a href="/productos/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:#2eacce;"></span><br>Productos</a>
						<a href="/productos/nuevo/" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:#2eacce;"></span> <br>Nuevo Producto</a>						
					</div>							
				</div>
			</div> 
  </div>
  <div class="col-md-4">
	<div class="row show-grid">
		<div class="col-md-12">
			<ul class="nav nav-pills nav-stacked">
				<li role="Información" class="menu-prod active informacion"><a class="options-prod" href="#producto-informacion">Información</a></li>
				<li role="Precio" class="menu-prod precio"><a class="options-prod" href="#producto-precio">Precio</a></li>
				<li role="Imagen" class="menu-prod imagen"><a class="options-prod" href="#producto-imagen">Imagen</a></li>
			</ul>
		</div>
	</div>
	<div class="row" id="cont-img-detalle">
		<div class="col-md-12">
			<a href="<?php echo $this->datos_editar->imagen; ?>" class="image-link">
			<img class="img-responsive img-rounded " src="<?php echo $this->datos_editar->imagen; ?>" >
			</a>
		</div>
	</div>
  </div>
 <div class="col-md-7 col-md-offset-1">
 
	<div id="producto-informacion" class="box-content">
    <form name="form1" method="post" action="" enctype="multipart/form-data" autocomplete="off">

	  <div class="form-group text-left title-head">
		<span>INFORMACIÓN</span>
      </div>      
      <div class="form-group">
		<div class="row">
			<div class="col-md-9">
				<label for="nombre">SKU (Code bar)</label>
				<input type="text" class="form-control" id="sku" name="sku" placeholder="SKU" required value="<?php echo ($this->datos_editar->sku!="")?$this->datos_editar->sku:""; ?>">
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="checkbox">  
					<div class="row">
						<div class="col-md-12">
							<label for="sin_sku"> <input type="checkbox"  name="sin_sku" id="sin_sku" value="1" <?php echo ($this->datos_editar->sin_sku!=0 AND $this->datos_editar->sin_sku!="")?"checked":""; ?> >Sin Código de Barra</label>
						</div>	
					</div>
				</div>		
			</div>	
			<div class="col-md-6">
				<div class="checkbox">  
					<div class="row">
						<div class="col-md-12">
							<label for="manejostock"> <input type="checkbox"  name="manejostock" id="manejostock" value="1" <?php echo ($this->datos_editar->manejostock!=0 AND $this->datos_editar->manejostock!="")?"checked":""; ?> >Con Manejo STOCK</label>
						</div>	
					</div>
				</div>		
			</div>				
		</div>		
	  </div>
      <div class="form-group">
		<div class="row">
			<div class="col-md-6">
			<label for="nombre">Categoría</label>
			<select class="form-control chosen-select" name="categoria" id="categoria" required>
			  <option value="">Seleccione una opción</option>
			  <?php if (count($this->categoria)) { ?>
				  <?php foreach ($this->categoria as $aux) { ?>  
				  <?php if($this->datos_editar->id_categoria == $aux->id){ ?>
				  <option selected value="<?php echo $aux->id;?>"><?php echo $aux->nombre;?></option>
				  <?php }else{ ?>
				  <option value="<?php echo $aux->id;?>"><?php echo $aux->nombre;?></option>
				  <?php }} ?>
			  <?php } ?>

			</select>
			</div>
			<div class="col-md-6">
				<label for="nombre">Nombre</label>
				<input type="hidden" class="form-control" id="id" name="id" value="<?php echo ($this->datos_editar->id!="")?$this->datos_editar->id:""; ?>">
				<input type="hidden" class="form-control" name="tipo-edit" value="producto-informacion">
				<input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre" required value="<?php echo ($this->datos_editar->nombre!="")?$this->datos_editar->nombre:""; ?>">				
			</div>
		</div>
      </div> 	  
      <div class="form-group">
        <label for="descripcion">Descripcion</label>
        <textarea class="form-control" id="descripcion" name="descripcion" style="height:120px;" ><?php echo ($this->datos_editar->descripcion!="")?$this->datos_editar->descripcion:""; ?></textarea>
      </div>
	  
      <div class="form-group">
		<div class="row">
			<div class="col-md-6">
				<label for="nombre">Estado</label>
				<select class="form-control chosen-select" name="estado" id="estado" required>
				  <option value="1" <?php if($this->datos_editar->estado!=""){ echo ($this->datos_editar->estado!=0)?"selected":""; } ?> >Activo</option>
				  <option value="0" <?php if($this->datos_editar->estado!=""){ echo ($this->datos_editar->estado!=1)?"selected":""; } ?>>Inactivo</option>
				</select>			
			</div>
		
		</div>
      </div>    
	  <div class="form-group text-right controls">
		<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Guardar</button>
      </div>  
    </form>
	</div>
	
	<div id="producto-precio" style="display:none;" class="box-content" >
    <form name="form2" method="post" action="" enctype="multipart/form-data" autocomplete="off">
	  <div class="form-group text-left title-head">
		<span>PRECIO</span>
      </div> 	
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<label for="valor">Precio</label>
					<div class="input-group">
						<div class="input-group-addon">$</div>
						<input type="hidden" class="form-control" id="id" name="id" value="<?php echo ($this->datos_editar->id!="")?$this->datos_editar->id:""; ?>">
						<input type="hidden" class="form-control" name="tipo-edit" value="producto-precio">						
						<input type="text" class="form-control" id="valor" placeholder="$" name="valor" required value="<?php echo ($this->datos_editar->valor!="")?$this->datos_editar->valor:""; ?>">
					</div>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<label for="costo">Costo</label>
					<div class="input-group">
						<div class="input-group-addon">$</div>
						<input type="text" class="form-control" id="costo" name="costo" placeholder="$" name="valor" required value="<?php echo ($this->datos_editar->costo!="")?$this->datos_editar->costo:""; ?>">
					</div>
				</div>
			</div>
		</div>		

		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<label for="valor">Precio Oferta</label>
					<div class="input-group">
						<div class="input-group-addon">$</div>
						<input type="text" class="form-control" id="valor_rebaja" placeholder="$" name="valor_rebaja"  value="<?php echo ($this->datos_editar->valor_rebaja!="")?$this->datos_editar->valor_rebaja:""; ?>">
					</div>
				</div>
			</div>   
		</div>	
		<div class="checkbox">  
			<div class="row">
				<div class="col-md-6">
					<label for="activar_vr"> <input type="checkbox"  name="activar_vr" id="activar_vr" value="1" <?php echo ($this->datos_editar->activar_vr!=0 AND $this->datos_editar->activar_vr!="")?"checked":""; ?> >Activar precio oferta</label>
				</div>	
			</div>
		</div>		
		<div class="form-group text-right controls">
			<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Guardar</button>
		</div>  
    </form>		
	</div>
	<div id="producto-imagen" style="display:none;" class="box-content">
		<form name="form3" method="post" action="" enctype="multipart/form-data" autocomplete="off">
		  <div class="form-group text-left title-head">
			<span>IMAGEN</span>
		  </div> 		
			<div class="form-group">
				<label for="imagen">Imagen</label>
				<input type="hidden" class="form-control" id="id" name="id" value="<?php echo ($this->datos_editar->id!="")?$this->datos_editar->id:""; ?>">
				<input type="hidden" class="form-control" name="tipo-edit" value="producto-imagen">				
				<input type="file" id="imagen" name="adjunto">
			</div>      
			<div class="form-group text-right controls">
				<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Guardar</button>
			</div>  
		</form>	
	</div>
  </div>
  </div>