<?php echo $this->navegacion(array($this->translate->_('Accesibilidad')=>$this->translate->_('accesibilidad')))?>

<div class="estilo-pag acc">
<h1><?php echo $this->translate->_('Accesibilidad'); ?></h1>
<p><?php echo $this->translate->_('Las teclas de acceso son un dispositivo de navegación que le permite navegar por este sitio web utilizando su teclado.'); ?></p>
<h3><?php echo $this->translate->_('Utilización de las teclas de acceso en su navegador web'); ?></h3>
<div class="explorer">
  <p class="text-sub-titulo">Explorer</p>
  <p><?php echo $this->translate->_('Mantenga pulsada la tecla'); ?> <strong>Alt</strong> <?php echo $this->translate->_('y presione el número de la'); ?> <strong><?php echo $this->translate->_('tecla de acceso'); ?></strong>.</p>
</div>
<div class="firefox">
  <p class="text-sub-titulo">Firefox 2 <?php echo $this->translate->_('y superiores'); ?> (Windows)</p>
  <p><?php echo $this->translate->_('Mantenga pulsada la tecla'); ?> <strong>Shift </strong>+ <strong>Alt</strong> <?php echo $this->translate->_('y presione el número de la'); ?> <strong><?php echo $this->translate->_('tecla de acce'); ?></strong><strong><?php echo $this->translate->_('so'); ?></strong>.</p>
</div>
<div class="opera">
  <p class="text-sub-titulo">Opera</p>
  <p> <?php echo $this->translate->_('Mantenga pulsada la tecla'); ?> <strong>Shift </strong>+<strong> Esc </strong><?php echo $this->translate->_('y presione el número de la'); ?> <strong><?php echo $this->translate->_('tecla de a'); ?></strong><strong><?php echo $this->translate->_('cceso'); ?></strong>.</p>
</div>
<div class="safari">
  <p class="text-sub-titulo">Safari</p>
  <p><?php echo $this->translate->_('Mantenga pulsada la tecla'); ?> <strong>Alt</strong> <?php echo $this->translate->_('y presione el número de la'); ?> <strong><?php echo $this->translate->_('tecla de acceso'); ?></strong>.</p>
</div>
<div class="chrome">
  <p class="text-sub-titulo">Chrome</p>
  <p><?php echo $this->translate->_('Mantenga pulsada la tecla'); ?> <strong>Alt</strong> <?php echo $this->translate->_('y presione el número de la'); ?> <strong><?php echo $this->translate->_('tecla de acceso'); ?></strong>.</p>
</div>
<h3><?php echo $this->translate->_('Teclas de acceso disponibles'); ?></h3>
<p><?php echo $this->translate->_('Este sitio utiliza una configuración que se acerca en detalle a la mayoría de las recomendaciones internacionales sobre las teclas de acceso. Estas son:'); ?></p>
<div class="editable">
  <ul>
    <li>Alt + 1 -> Quiénes somos</li>
    <li>Alt + 2 -> Responsabilidad Social</li>
    <li>Alt + 3 -> Productos</li>
	<li>Alt + 4 -> Contacto</li>
  </ul>
</div>
<p><?php echo $this->translate->_('Puede encontrar más información sobre las teclas de acceso en'); ?> <a onclick="this.target='_blank'" onkeypress="this.target='_blank'" href="http://www.discapnet.es/web_accesible/wcag10/WAI-WEBCONTENT-19990505_es.html"><?php echo $this->translate->_('Directrices de  Accesibilidad del W3C.'); ?></a></p>
</div>