<div class="container">
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h3 style="margin-bottom:0px;" ><?php echo $this->title;?></h3>
    </div>
  </div>
  <div class="col-md-12">
    <form name="form1" method="post" action="" autocomplete="off">
		<div class="row-fluid">
			<div class="col-md-3">
			  <div class="form-group">
					<select class="form-control chosen-select" id="select-reporte">
						<option value="">Seleccione Reporte</option>
						<option value="1">Total Productos Vendidos</option>
						<option value="2">Total Categorias Vendidas</option>
						<option value="3">Total Ventas por Vendedor</option>
						<option value="4">Ventas Mensuales</option>
					</select>
			  </div>				
			</div>
			<div class="col-md-2" id="content_anio" style="display:none;">
				<div class="form-group">
					<select class="form-control" id="anio" disabled >
						<option value="" selected >Seleccione Año</option>
						<option value="2016">2016</option>
						<option value="2017">2017</option>
						<option value="2018">2018</option>
					</select>
				</div>
			</div>	
			<div class="col-md-2" id="content_mes_user" style="display:none;">
				<div class="form-group">
					<select class="form-control" id="mes_user" disabled >
						<option value="0" selected >Seleccione Mes</option>
						<option value="01">Enero</option>
						<option value="02">Febrero</option>
						<option value="03">Marzo</option>
						<option value="04">Abril</option>
						<option value="05">Mayo</option>
						<option value="06">Junio</option>
						<option value="07">Julio</option>
						<option value="08">Agosto</option>
						<option value="09">Septiembre</option>
						<option value="10">Octubre</option>
						<option value="11">Noviembre</option>
						<option value="12">Diciembre</option>
					</select>
				</div>
			</div>	
			<div class="col-md-2" id="content_anio_user" style="display:none;">
				<div class="form-group">
					<select class="form-control" id="anio_user" disabled >
						<option value="" selected >Seleccione Año</option>
						<option value="2016">2016</option>
						<option value="2017">2017</option>
						<option value="2018">2018</option>
					</select>
				</div>
			</div>				
		</div>
		<div class="row-fluid">
			<div class="col-md-12">
			<table id="table-load-reporte" class="table table-bordered table-hover">
				
			</table>
			</div>
		</div>
    </form>
  </div>

<div class="modal fade" id="modal_grafico" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
			<div id="chart_div" ></div>
    </div>
  </div>
</div>

</div>
</div>




