<div class="container">
	<div class="row">
	  
		<div class="col-md-12">
			<div class="page-header">
			  <h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div> 
		</div>	  

		<div class="col-md-3 txt-ayuda">
			<h4>Información</h4>
			
			<p>Mantén tus datos actualizados para el buen uso del sistema, asi podras recuperar información en caso de un eventual problema con tu cuenta.</p>
		</div>
		<div class="col-md-4">
			<div class="row show-grid bbottom">
				<div class="col-md-12">
					<form name="form1" id="form1" method="post" action="" autocomplete="off" >    
					  <div class="form-group">
						<input type="text" class="form-control" id="nombre_user" name="nombre_user" value="<?php echo ($this->datos_usuario->nombre!="")?$this->datos_usuario->nombre:"";?>" required placeholder="Nombre Completo" >  
					  </div> 
					  <div class="form-group">
						<input type="email" class="form-control" id="email" name="email" value="<?php echo ($this->datos_usuario->email!="")?$this->datos_usuario->email:"";?>" required placeholder="Correo Electrónico" >  
					  </div>    
					  <button type="submit" class="btn btn-primary">Guardar cambios</button>
					</form>
				</div>
			</div>  

			<div class="row show-grid bbottom">
				<div class="col-md-12">
					<form name="form-pass" id="form-pass" method="post" action="" autocomplete="off"  >
					  <div class="form-group">
						<input type="password" class="form-control" id="password_actual" name="password_actual" value="" required maxlength="12" placeholder="Actual" autocomplete="off" >
					  </div>      
					  <div class="form-group">
						<input type="password" class="form-control" id="password2" name="password2" value="" required maxlength="12" placeholder="Nueva" autocomplete="off" >
					  </div>
					  <div class="form-group">
						<input type="password" class="form-control" id="password3" name="password3" value="" required maxlength="12" placeholder="Repetir contraseña nueva" autocomplete="off" >
					  </div>  
					  <button type="submit" class="btn btn-primary">Guardar cambios</button>
					</form>
				</div>
			</div>
		</div>

	</div>
</div>
