<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-6">
						<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
						</div>
						<div class="col-md-6 col-md-offset-2 col-sm-6 col-sm-offset-2 col-xs-6 text-right">
							<a href="/usuarios/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:#2eacce;"></span><br>Usuarios</a>
						</div>							
					</div>
			</div> 
		</div>  
		<div class="col-md-4">
			<form name="form1" id="form1" method="post" action="" autocomplete="off">

			  <div class="form-group">
				<label for="usuario">Usuario</label>
				<input type="text" maxlength="50" class="form-control" id="usuario" name="usuario" placeholder="Usuario" value="">
			  </div>



			  <div class="form-group">
				<label for="nombre">Nombre Completo</label>
				<input type="text" class="form-control" id="nombre" maxlength="100" name="nombre" placeholder="Nombre Apellido" required value="">
			  </div>
			  <div class="form-group">
				<label for="tipo">Tipo</label>
				  <select name="tipo" class="form-control chosen-select">
					
					<option  value="1">Administrador</option>
					<option  value="2">Vendedor</option>
				  </select>
			  </div>

			  <div class="form-group">
				<label for="email">Email</label>
				  <input type="email" class="form-control" maxlength="249" id="email" placeholder="example@mail.com" name="email" required value="<?php echo ($this->datos_editar->email!="")?$this->datos_editar->email:""; ?>">
			  </div>  
			  <div class="form-group">
				<label for="estado">Estado</label>
				  <select name="estado" class="form-control">
					
					<option value="1">Activo</option>
					<option value="2">Inactivo</option>
				  </select>
			  </div>	  
			  <button type="submit" class="btn btn-primary">Guardar cambios</button>
			</form>
		</div>
	</div>
</div>