<div class="container">
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-6">
				<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
				</div>
				<div class="col-md-6 col-md-offset-2 col-sm-6 col-sm-offset-2 col-xs-6 text-right">
				
				<a href="/usuarios/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:#2eacce;"></span><br>Usuarios</a>
				<?php if($this->session_usu->tipo == 1){ ?>
				<a href="/usuarios/nuevo/" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:#2eacce;"></span> <br>Añadir Usuario</a>
				<?php } ?>						
				</div>							
			</div>
		</div> 
	</div>  


	<div class="col-md-4">
		<form name="form1" id="form1" method="post" action="" autocomplete="off">

		  <div class="form-group">
			<label for="usuario">Usuario</label>
			<input type="hidden" class="form-control" id="id" name="id" value="<?php echo ($this->datos_editar->id!="")?$this->datos_editar->id:""; ?>">
			<input type="text" maxlength="50" class="form-control" id="usuario" name="usuario" placeholder="Usuario" value="<?php echo ($this->datos_editar->usuario!="")?$this->datos_editar->usuario:""; ?>">
		  </div>



		  <div class="form-group">
			<label for="nombre">Nombre Completo</label>
			<input type="text" class="form-control" id="nombre" maxlength="100" name="nombre" placeholder="Nombre Apellido" required value="<?php echo ($this->datos_editar->nombre!="")?$this->datos_editar->nombre:""; ?>">
		  </div>
		  <div class="form-group">
			<label for="tipo">Tipo</label>
			  <select name="tipo" class="form-control chosen-select">
				
				<option <?php echo ($this->datos_editar->tipo == 1 )?"selected":"" ?> value="1">Administrador</option>
				<option <?php echo ($this->datos_editar->tipo == 2 )?"selected":"" ?> value="2">Vendedor</option>
			  </select>
		  </div>

		  <div class="form-group">
			<label for="email">Email</label>
			  <input type="email" class="form-control" maxlength="249" id="email" placeholder="example@mail.com" name="email" required value="<?php echo ($this->datos_editar->email!="")?$this->datos_editar->email:""; ?>">
		  </div>  
		  <div class="form-group">
			<label for="comision">Comisión</label>
			  <input type="text" class="form-control" maxlength="3" id="comision" placeholder="%" name="comision" required value="<?php echo ($this->datos_editar->comision!="")?$this->datos_editar->comision:""; ?>">
		  </div>                     
		  <div class="form-group">
			<label for="estado">Estado</label>
			  <select name="estado" class="form-control">
				
				<option <?php echo ($this->datos_editar->estado == 1 )?"selected":"" ?> value="1">Activo</option>
				<option <?php echo ($this->datos_editar->estado == 2 )?"selected":"" ?> value="2">Inactivo</option>
			  </select>
		  </div>	  
		  <button type="submit" class="btn btn-primary">Guardar cambios</button>
		</form>
	</div>
</div>
</div>