
  
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Ingrese Password</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="/usuarios/pass/<?php echo $this->id; ?>" name="form-pass" id="form-pass">
          <div class="form-group">
            <label for="recipient-name" class="control-label">Password</label>
            <input type="text" class="form-control" id="password" name="password">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="guardar">Guardar</button>
      </div>
      <script type="text/javascript">
        $(function(){

            $("#guardar").click(function(){

              $("#form-pass").submit();

            })

        })
      </script>
      

