<div class="container">
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
		<div class="row">
			<div class="col-md-6">
			<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div>
			<div class="col-md-6 text-right">
					<a href="/movimientos/nuevo/" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:#2eacce;"></span> <br>Añadir Movimiento</a>
			</div>
		</div>
    </div> 
  </div>

  <div class="col-md-12">
    <div class="panel panel-default">
    <div class="panel-body">
      <!-- Table -->
      <table class="table table-bordered table-hover" id="table-mov">
        <thead>
        <tr>
			
          <th>Tipo</th>
          <th>ID Movimiento</th>
          <th>Fecha</th>
          <th>Producto</th>
          <th>Cantidad</th>
		  
	  
		  
        </tr>
        </thead>

        <tbody>
          <?php if (count($this->movimientos)) { ?>
              <?php foreach ($this->movimientos as $aux) { ?>    
                <tr>
                  <td><?php echo $aux->tipo;?>  <?php echo ($aux->tipo == 'Entrada')?'<span class="glyphicon glyphicon-arrow-right text-success" aria-hidden="true"></span>':'<span class="glyphicon glyphicon-arrow-left text-danger" aria-hidden="true"></span>'; ?> </td>
                  <td><?php echo $aux->id;?></td>
                  <td><?php echo $aux->fecha;?></td>
                  <td><?php echo '[<strong>'.$aux->sku.'</strong>] '.$aux->nombre_producto;?></td>
                  <td><?php echo $aux->cantidad;?></td>
                
                </tr>
              <?php } ?>
          <?php }else{ ?>
                <tr>
                  <td colspan="5" align="center">No existen movimientos</td>
                </tr>
          <?php } ?>
          
        </tbody>  

      </table>
    </div>
  </div>
</div>
</div>
</div>