<div class="container">
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
		<div class="row">
			<div class="col-md-6">
				<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div>
			<div class="col-md-6 text-right">
				<a href="/productos/categoria/nuevo/" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:#2eacce;"></span> <br>Añadir Categoría</a>
			</div>
			
		</div>
	</div> 
  </div>
  
  
  <div class="col-md-12">
    <div class="panel panel-default">
	
		<div class="panel-body">
		  <!-- Table -->
		  <table class="table table-hover table-bordered" id="table-categoria">
			<thead>
			<tr>
			  <th>Código</th>	
			  <th>Nombre</th>	
			  <th>Nombre corto</th>
			  <th>Estado</th>
			  <th style="width:130px;"></th>
			</tr>
			</thead>

			<tbody>
			  <?php if (count($this->categoria)) { ?>
				  <?php foreach ($this->categoria as $aux) { ?>    
					<tr>
					  <td><?php echo $aux->id;?></td>
					  <td><?php echo $aux->nombre;?></td>
					  <td><?php echo $aux->nombre_corto;?></td>
					  <td><?php echo ($aux->estado!=1)?"<span class='glyphicon glyphicon-remove'  style='color:red;'></span>":"<psan class='glyphicon glyphicon-ok' style='color:green;'></span>";?></td>
					  
					  <td>
						<div class="btn-group">
						  <button type="button" class="btn btn-default btn-sm btn-editar" value="<?php echo $aux->id;?>" ><span class="glyphicon glyphicon-pencil" aria-hidden="true" style="color:#555;"></span> Modificar</button>
						  <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<span class="caret"></span>
							<span class="sr-only">Toggle Dropdown</span>
						  </button>
						  <ul class="dropdown-menu">
							<li><a href="/productos/categoria/eliminar/<?php echo $aux->id;?>/" class="eliminar"><span class="glyphicon glyphicon-trash" aria-hidden="true" style="color:#555;"></span> Eliminar</a></li>
						  </ul>
						</div>
						
					  </td> 
					</tr>
				  <?php } ?>
			  <?php }else{ ?>
					<tr>
					  <td colspan="12" align="center">No existen Categorias</td>
					</tr>
			  <?php } ?>
			  
			</tbody>  

		  </table>
		</div>
	</div>
  </div>
 
</div>
</div>