<div class="container">
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
		<div class="row">
			<div class="col-md-4 col-sm-4 col-xs-6">
			<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div>
			<div class="col-md-6 col-md-offset-2 col-sm-6 col-sm-offset-2 col-xs-6 text-right">
				<a href="/productos/categoria/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:#2eacce;"></span><br>Categorías</a>
			</div>							
		</div>
    </div> 
  </div>
  <div class="col-md-4">
	<ul class="nav nav-pills nav-stacked">
		<li role="Información" class="menu-prod active informacion"><a class="options-prod" href="#producto-informacion">Información</a></li>
	</ul>
  </div>
 <div class="col-md-7 col-md-offset-1">
 
	<div id="producto-informacion" class="box-content">
    <form name="form1" id="form1" method="post" action="">

	  <div class="form-group text-left title-head">
		<span>INFORMACIÓN</span>
      </div>      
      <div class="form-group">
        <label for="nombre">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre categoría" required value="<?php echo ($this->datos_editar->nombre!="")?$this->datos_editar->nombre:""; ?>">
      </div>
      <div class="form-group">
        <label for="nombre_corto">Nombre corto</label>
        <input type="text" class="form-control" id="nombre_corto" name="nombre_corto" placeholder="Nombre corto" value="<?php echo ($this->datos_editar->nombre_corto!="")?$this->datos_editar->nombre_corto:""; ?>">
      </div>	    
      <div class="form-group">
		<div class="row">
			<div class="col-md-6">
				<label for="nombre">Estado</label>
				<select class="form-control chosen-select" name="estado" id="estado" required>
				  <option value="1" <?php if($this->datos_editar->estado!=""){ echo ($this->datos_editar->estado!=0)?"selected":""; } ?> >Activo</option>
				  <option value="0" <?php if($this->datos_editar->estado!=""){ echo ($this->datos_editar->estado!=1)?"selected":""; } ?>>Inactivo</option>
				</select>			
			</div>
		
		</div>
      </div>    
	  <div class="form-group text-right controls">
		<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Guardar</button>
      </div>  
    </form>
	</div>
  </div>
 </div>
 </div>