<?php echo $this->doctype();echo "\n"; ?>
<!--[if IE 6]>
<html id="ie6" class="ancient-ie old-ie no-js" lang="es-ES">
<![endif]-->
<!--[if IE 7]>
<html id="ie7" class="ancient-ie old-ie no-js" lang="es-ES">
<![endif]-->
<!--[if IE 8]>
<html id="ie8" class="old-ie no-js" lang="es-ES">
<![endif]-->
<!--[if IE 9]>
<html id="ie9" class="old-ie9 no-js" lang="es-ES">
<![endif]-->
<!--[if !(IE 6) | !(IE 7) | !(IE 8)  ]><!-->
<html class="no-js" lang="es-ES">
<!--<![endif]-->

<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <?php echo $this->headMeta(); echo "\n"; ?>
    <?php echo $this->headTitle(); echo "\n"; ?>
    <?php echo $this->headLink(); echo "\n"; ?>
    <?php echo $this->headScript(); echo "\n"; ?>
	<link rel="shortcut icon" href="/imagenes/sitio/favicon.ico">
	
</head>
<body >
<div id="load" style="display:none;">
	<div class="cssload-aim"></div>
</div>

<div id="wrapper">
	<div id="fondo">
		<!--[TOP]-->
		<?php echo $this->action("top","layout"); ?>
		<!--[HEADER]-->
		<?php echo $this->action("main","layout"); ?>
		<!--[CONTENIDO]-->
		<div id="contenido">
		<?php echo $this->layout()->content;?>
	
		</div>
		<!--[FOOTER]-->
		<?php echo $this->action("footer","layout"); ?>
	</div>
	<div class="modal fade" id="modal_grafico_resumen" tabindex="-1" role="dialog" aria-labelledby="modal_grafico_resumen">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="modal_grafico_resumen">Resumen</h4>
		  </div>
		  <div class="modal-body">
			<div id="chart_div_cat_p_prod"  ></div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		  </div>
		</div>
	  </div>
	</div>	
</div>
<div class="impreso">
</div>
<div id="mensaje-load">
</div>
</body>
<script>
	<?php //echo "alert(".$this->current2.");";?>
	$(function(){
	               $(document).ready(function(){ 
						<?php  if(isset($this->current)){ ?>	
							$("#<?php echo $this->current ?>").addClass("active");
						<?php } if(isset($this->current2)){ ?>
							$("#<?php echo $this->current2 ?>").addClass("active");
						<?php } ?> 	
						
						$("#alert-esp").fadeOut(7000);
	               });		
		
	});
</script>
</html>

<div class="modal fade" id="" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
			
    </div>
  </div>
</div>



