<div class="container">
	<div class="row">
	  <div class="col-md-12">

    <div class="page-header">
		<div class="row">
			<div class="col-md-6">
				<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div>
			<div class="col-md-6 text-right">
				<a href="/clientes/" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:#2eacce;"></span> <br>Clientes</a>
				<a href="/clientes/nuevo/" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:#2eacce;"></span> <br>Añadir Cliente</a>
			</div>
			
		</div>
	</div>
	  </div>
	  <div class="col-md-4">
		<form name="form1" id="form1" method="post" action="" autocomplete="off">

		  <div class="form-group">
			<label for="usuario">RUT</label>
			<input type="hidden" class="form-control" id="tipo" name="tipo" value="1" >
			<input type="text" class="form-control" id="rut" name="rut" placeholder="RUT" required value="<?php echo ($this->cliente->rut!="")?$this->cliente->rut:''; ?>" >
		  </div>
		  <div class="form-group">
			<label for="nombre">Nombre Completo</label>
			<input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre Apellido" required value="<?php echo ($this->cliente->nombre!="")?$this->cliente->nombre:''; ?>" >
		  </div>
		  <div class="form-group"> 
			<label for="telefono">Teléfono</label>
			<input type="number" class="form-control" id="telefono" name="telefono" placeholder="Número de Celular" value="<?php echo ($this->cliente->telefono!="")?$this->cliente->telefono:''; ?>" >
		  </div>

		  <div class="form-group">
			<label for="email">Email</label>
			  <input type="email" class="form-control" id="email" placeholder="example@mail.com" name="email" value="<?php echo ($this->cliente->email!="")?$this->cliente->email:''; ?>" >
		  </div>  
		  <div class="form-group">
			<label for="direccion">Dirección</label>
			<input type="direccion" class="form-control" id="direccion" placeholder="Calle, N° casa, sector" name="direccion" value="<?php echo ($this->cliente->direccion!="")?$this->cliente->direccion:''; ?>" >
		  </div>	  
		  <button type="submit" class="btn btn-primary">Guardar</button> 
		</form>
	  </div>

	</div>
</div>



