<div class="container-fluid">
<div class="row">
  <div class="col-md-12">

    <div class="page-header">
		<div class="row">
			<div class="col-md-6">
				<h3 style="margin-bottom:0px;"><?php echo $this->title;?></h3>
			</div>
			<div class="col-md-6 text-right">
				<a href="/clientes/nuevo/" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:#2eacce;"></span> <br>Añadir Cliente</a>
			</div>
			
		</div>
	</div>
  </div>
  <div class="col-md-12">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      
    <div class="panel-body">
      <!-- Table -->
      <table class="table table-hover table-bordered" id="table-clientes">
        <thead>
        <tr>
          <th>RUT</th>
          <th>Nombre</th>
          <th>Teléfono</th>
          <th>Email</th>
          <th>Dirección</th>
          <th>Acción</th>
        </tr>
        </thead>

        <tbody id="listado">
        </tbody>  

      </table>  
	</div>
  </div>
</div>
</div>
</div>



